In [10]:
#Below are the steps need to perform data analysis on given datasets
#Gathering or collecting of the data
#Cleaning a data(Removing noise,duplicate rows or NAN value if exist) 
#Performing analysis of the data(mean,min,max,mode,medium value)
#Plot the results using matplotlib,seaborn visualization library
#Communicate the insights with client or management 
#Futher classic ml model can be applied as well as feature Engineering and cross validation can be done.
import pandas as pd
import numpy as nm
import matplotlib.pyplot as mat
import seaborn as sns
csv_path ="E:\data.csv"

#Read the csv file and convert into pandas 
data = pd.read_csv(csv_path)
#print complete data set
#print (data)

#display first 10 row
print("!!!.....head data....!!!",data.head(10))

#display last 10 row
print("!!!....tail data ...!!!",data.tail(10))
#Replace all NAN value if there is any NAN value exist in dataset
data=data.duplicated()
print("data after removing duplicate row",data)
#Replace the nan value with zero
data = data.fillna(0)
print("data are mention below",data)
#shape of data
shape = data.shape
print("Shape of data",shape)

#decription of the data
description = data.describe()
print("description of data",description)


print("information of the data",data.info())

label = data['label']
print(label)
#This will filter the data from the Data frame 
data_c =data.iloc[:, 2:211]
print("data from column........!!",data_c)

#Find maximum value of each column
maximum=data_c.max()
print("Maximum data in each column",maximum)
list_value =range(0,208)
mat.pie(list_values,labels=None,autopct='%0.1f%%',shadow=False,startangle=90)
mat.show()

#Find minimum value in each column
minimum =data_c.min()
print("Minimum data in each column",minimum)
data1=sns.lmplot(x="id",y="minimum value",data =minimum,order = 2, ci = None)

#Find mean of each column
mean_data =data_c.mean()
print("Mean data in each column",mean_data)
data2=sns.lmplot(x="id",y="mean value",data =mean_data,order = 2, ci = None)

#Find median of each column
median_data =data_c.median()
print("Median data in each column",median_data)
data3=sns.lmplot(x="id",y="medium value",data =medium_data,order = 2, ci = None)

#Find mode in each colum
mode_data = data_c.mode()
print("Mode of data in each column",mode_data)
data4=sns.lmplot(x="id",y="mode_data",data =mode_data,order = 2, ci = None)

!!!.....head data....!!!    id  label           0           1           2           3           4  \
0   0      1  269.909900  245.022455  236.823653  236.054239  226.653206
1   1      0  268.835447  255.128640  246.701954  242.036672  233.909313
2   2      1  249.814868  238.143049  225.509790  224.020928  221.349896
3   3      1  265.645330  254.075815  244.410179  237.205829  228.199419
4   4      1  252.877477  242.643030  234.194391  230.216435  224.971707
5   5      0  269.007832  256.340300  243.373009  244.973729  236.217629
6   6      1  257.134605  245.554606  238.301205  233.584067  226.839904
7   7      0  264.421179  254.825260  247.305526  236.258199  232.487453
8   8      1  262.443435  242.482184  235.243081  229.671630  220.534840
9   9      1  272.477025  255.862125  247.440610  237.717413  229.176902

            5           6           7  ...        199        200        201  \
0  224.404685  220.851245  214.977137  ...  84.714461  85.070369  80.791612
1  232.043345  222.124869  219.940031  ...  84.722024  83.998053  84.790507
2  220.661538  218.693435  216.288675  ...  88.551575  85.730525  85.746395
3  225.220112  216.406038  217.047009  ...  85.396405  84.945310  87.353371
4  228.850109  221.541657  214.451354  ...  81.886134  81.901487  84.380851
5  234.587302  225.677855  220.978063  ...  81.931721  81.073793  82.408617
6  223.618404  215.332872  213.858101  ...  83.010440  82.781932  84.143535
7  226.445845  217.546324  212.868252  ...  86.945631  87.497159  86.658212
8  220.689546  216.703747  213.332251  ...  84.668809  83.648363  81.032943
9  227.239632  219.224787  216.418312  ...  86.810566  88.950575  86.723207

         202        203        204        205        206         207  \
0  85.043619  86.165863  86.142181  87.240098  86.661944   87.161127
1  81.817250  86.258496  83.141134  77.692364  83.453963   83.085457
2  85.454112  83.327379  86.615489  91.204152  92.125394  100.590875
3  87.569690  86.940543  90.258793  87.618796  91.097681   91.694970
4  81.659147  78.206074  84.195057  77.831454  80.556957   85.095413
5  80.873046  80.282974  82.672176  81.615222  84.817889   82.537892
6  83.879879  85.028087  83.020614  82.265263  84.083959   86.736579
7  85.699479  84.625597  86.312405  84.492377  84.833866   86.147805
8  83.540640  83.581133  83.842005  84.918132  80.132367   83.079107
9  90.598043  91.322091  89.435149  86.702477  93.995637   92.229516

          208
0   84.570631
1   84.011231
2  100.373680
3   99.870002
4   84.478315
5   81.143042
6   83.107070
7   84.232788
8   80.696886
9   94.476133

[10 rows x 211 columns]
!!!....tail data ...!!!         id  label           0           1           2           3           4  \
2576  2576      1  267.649165  255.174699  249.318755  242.431815  233.233941
2577  2577      1  268.210524  254.375971  246.224587  236.421866  228.933981
2578  2578      1  268.143456  257.379418  246.377839  239.813611  229.433808
2579  2579      1  258.703080  242.941850  241.009629  235.256666  226.679142
2580  2580      1  253.850750  242.869424  226.943352  223.277254  218.649093
2581  2581      0  265.478554  248.456700  239.650565  230.677408  225.210581
2582  2582      1  261.086370  254.302552  241.267966  237.664339  229.137569
2583  2583      0  270.580657  251.392862  241.798424  232.749997  223.231755
2584  2584      0  269.094876  258.980580  243.346779  243.345013  236.217876
2585  2585      1  270.629464  251.100649  245.058526  235.730927  229.231039

               5           6           7  ...        199        200  \
2576  230.123629  223.151174  221.018220  ...  82.148684  86.599898
2577  225.464967  218.787120  218.494406  ...  88.052778  86.861965
2578  226.630113  220.614369  217.221438  ...  87.917012  87.030311
2579  227.894496  220.663374  210.443729  ...  84.484408  82.348363
2580  222.056540  215.262654  211.192740  ...  80.643262  80.025241
2581  221.804600  217.418677  210.839031  ...  86.644784  88.880747
2582  225.528770  219.778795  214.029566  ...  80.823018  84.436321
2583  227.217593  216.666280  214.888719  ...  89.955675  88.144260
2584  232.820236  228.295468  221.449015  ...  87.507606  83.553445
2585  224.757355  220.225319  217.461614  ...  89.387830  88.252567

            201        202        203        204        205        206  \
2576  82.685156  85.039666  88.792476  85.663241  87.166414  87.033486
2577  88.954600  86.923335  89.916924  88.924808  89.585558  91.084695
2578  87.627294  87.919210  88.221045  90.997884  89.030498  89.195357
2579  79.382071  83.658923  85.627422  82.197463  86.659997  83.056237
2580  83.091966  82.643577  83.389646  80.342349  81.883297  79.614725
2581  85.538684  81.705829  89.691881  88.302796  85.959626  92.702906
2582  86.679120  82.381398  84.009289  85.544840  77.717334  79.209919
2583  85.766380  88.629346  86.940850  88.869495  93.993647  90.440840
2584  88.372842  86.209850  80.870208  83.784725  90.330963  84.427951
2585  88.512544  90.276785  92.918003  89.230941  91.098583  93.972117

            207         208
2576  83.156024   89.368592
2577  98.337512   97.723616
2578  97.933219   90.775216
2579  78.035117   83.971043
2580  83.622524   76.275554
2581  91.191205  100.192325
2582  82.191258   81.808620
2583  88.571121   98.488771
2584  86.449653   88.205995
2585  91.921483   96.221401

[10 rows x 211 columns]
data after removing duplicate row 0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
2556    False
2557    False
2558    False
2559    False
2560    False
2561    False
2562    False
2563    False
2564    False
2565    False
2566    False
2567    False
2568    False
2569    False
2570    False
2571    False
2572    False
2573    False
2574    False
2575    False
2576    False
2577    False
2578    False
2579    False
2580    False
2581    False
2582    False
2583    False
2584    False
2585    False
Length: 2586, dtype: bool
data are mention below 0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
2556    False
2557    False
2558    False
2559    False
2560    False
2561    False
2562    False
2563    False
2564    False
2565    False
2566    False
2567    False
2568    False
2569    False
2570    False
2571    False
2572    False
2573    False
2574    False
2575    False
2576    False
2577    False
2578    False
2579    False
2580    False
2581    False
2582    False
2583    False
2584    False
2585    False
Length: 2586, dtype: bool
Shape of data (2586,)
description of data count      2586
unique        1
top       False
freq       2586
dtype: object

IndexingError: Too many indexers